#!/usr/bin/make -f
.PHONY: all clean
all: Lecture01 Lecture02 Lecture03 Lecture04 Lecture05 Lecture06 Lecture07 Lecture08 Lecture09 Lecture10 Lecture11 Lecture14 Lecture15 Lecture16 Lecture17 Lecture18

Lecture01: %: %.tex
	latexmk -pdf $@

Lecture02: %: %.tex
	latexmk -pdf $@

Lecture03: %: %.tex
	latexmk -pdf $@

Lecture04: %: %.tex
	latexmk -pdf $@

Lecture05: %: %.tex
	latexmk -pdf $@

Lecture06: %: %.tex
	latexmk -pdf $@

Lecture07: %: %.tex
	latexmk -pdf $@

Lecture08: %: %.tex
	latexmk -pdf $@

Lecture09: %: %.tex
	latexmk -pdf $@

Lecture10: %: %.tex
	latexmk -pdf $@

Lecture11: %: %.tex
	latexmk -pdf $@

Lecture14: %: %.tex
	latexmk -pdf $@

Lecture15: %: %.tex
	latexmk -pdf $@

Lecture16: %: %.tex
	latexmk -pdf $@

Lecture17: %: %.tex
	latexmk -pdf $@

Lecture18: %: %.tex
	latexmk -pdf $@

.PHONY: clean
clean:
	latexmk -C
